import type { Metadata } from "next";
import { Menu } from "@/components/Menu";
import { Footer } from "@/components/Footer";
import localFont from "next/font/local";
import "./globals.css";

import {Comic_Neue} from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const comic = Comic_Neue(
  {
    weight: ["300", "400", "700"],
    style: "normal",
    variable: "--comic",
    subsets: ["latin"]
  }
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comic.variable} antialiased font-comic`}>
        <Menu op1="fetch" op2="axios" op3="server_side"/>
        {children}

        <Footer op1="Nos contate: " op2="41 997744814"/>
      </body>
    </html>
  );
}
